{{ if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
---
apiVersion: v1
data:
  password: {{ .Values.prometheus.username }}
  username: {{ .Values.prometheus.password }}
kind: Secret
metadata:
  name: {{ .Values.prometheus.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opensearch-clusters-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/vendor: kubesphere
    {{- include "opensearch-operator.labels" . | nindent 4 }}
    {{- if .Values.customLabels.serviceMonitor.labels }}
    {{- toYaml .Values.customLabels.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: {{ .Values.prometheus.secretName }}
      username:
        key: username
        name: {{ .Values.prometheus.secretName }}
    path: /_prometheus/metrics
    port: http
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      opster.io/exporter-monitor: "yes"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: logstash-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/vendor: kubesphere
    {{- include "opensearch-operator.labels" . | nindent 4 }}
    {{- if .Values.customLabels.serviceMonitor.labels }}
    {{- toYaml .Values.customLabels.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: exporter
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      opster.io/logstash-exporter-monitor: "yes"
{{ end }}
